# Working through CSMGem examples

* Look at a series of compositions and compare the CSMGem output with my output
* Primarily targeting the C1, C2, C3 system
* P-T conditions for right now are going to be roughly 6C, 70 bar

In [1]:
import flashalgorithm as fc
import component_properties as comp_table
import vlhc_srk_eos as hc
import aq_hb_eos as aq
import h_vdwpm_eos as hyd
import numpy as np

In [2]:
def make_pretty_output(output, flash):
    stable_dict = {phase: ii for ii, (phase, alpha) in 
                   enumerate(zip(flash.phases, flash.alpha_calc)) 
                   if alpha > 1e-10}
    print('Calculation considers the following phases:\n{0}\n'.format(flash.phases))
    print('The stable phases are:')
    for phase, index in stable_dict.items():
        print('\n{0}: {1:3.5f} mol.%'.format(phase, flash.alpha_calc[index]))
        for ii, comp in enumerate(flash.compobjs): 
            print('\twith {0:3.5f} mol.% {1}'.format(
                flash.x_calc[ii, index],
                comp.compname))



In [3]:
comps_iter1 = ['water', 'methane']
x = np.asarray([0.5, 0.5])
P = 70 # bar
T = 273.15 + 6 # Kelvin

In [4]:
flash_iter1 = fc.FlashController(components=comps_iter1)
output = flash_iter1.main_handler(
            compobjs=flash_iter1.compobjs, 
            z=x, 
            T=T, 
            P=P)
make_pretty_output(output, flash_iter1)

Calculation considers the following phases:
['aqueous', 'vapor', 'lhc', 's1', 's2']

The stable phases are:

s1: 0.58264 mol.%
	with 0.85802 mol.% h2o
	with 0.14198 mol.% ch4

vapor: 0.41736 mol.%
	with 0.00018 mol.% h2o
	with 0.99982 mol.% ch4


In [5]:
sh = flash_iter1.fug_list[-1]
print(sh.hydrate_size(T, P, sh.v_H_0, sh.kappa_func(sh.Y_large)))
print(sh.v_H_0)
print(sh.kappa_func(sh.Y_large))
print(sh.Y_small, sh.Y_large)
print(np.exp(-3e-6*(69)))
print(np.exp(2.029776e-4*(279.15-298.15) + 1.1851168e-7*(279.15-298.15)**2) + -1.879455e-10*(279.15-298.15)**3)

22.1679043155
22.2566524253
3e-06
[ 0.          0.89908583] [ 0.          0.97781486]
0.999793021423
0.996194760702


In [6]:
comps_iter2 = ['water', 'ethane']

In [7]:
flash_iter2 = fc.FlashController(components=comps_iter2)
output = flash_iter2.main_handler(
            compobjs=flash_iter2.compobjs, 
            z=x, 
            T=T, 
            P=P)
make_pretty_output(output, flash_iter2)

Calculation considers the following phases:
['aqueous', 'vapor', 'lhc', 's1', 's2']

The stable phases are:

lhc: 0.43513 mol.%
	with 0.00008 mol.% h2o
	with 0.99992 mol.% c2h6

s1: 0.56487 mol.%
	with 0.88510 mol.% h2o
	with 0.11490 mol.% c2h6


In [8]:
comps_iter3 = ['water', 'propane']

In [9]:
flash_iter3 = fc.FlashController(components=['water', 'propane'],
                                phases=('aqueous', 'vapor', 'lhc'))
output = flash_iter3.main_handler(
            compobjs=flash_iter3.compobjs, 
            z=x, 
            T=T, 
            P=P)
make_pretty_output(output, flash_iter3)

Calculation considers the following phases:
['aqueous', 'vapor', 'lhc']

The stable phases are:

lhc: 0.49987 mol.%
	with 0.00011 mol.% h2o
	with 0.99989 mol.% c3h8

aqueous: 0.50013 mol.%
	with 0.99964 mol.% h2o
	with 0.00036 mol.% c3h8


In [10]:
flash_iter4 = fc.FlashController(components=comps_iter3,
                                phases=('aqueous', 'vapor', 'lhc', 's1', 's2'))
output = flash_iter4.main_handler(
            compobjs=flash_iter4.compobjs, 
            z=x, 
            T=276.15, 
            P=P,
            incipient_calc=True)
make_pretty_output(output, flash_iter4)

Calculation considers the following phases:
['aqueous', 'vapor', 'lhc', 's1', 's2']

The stable phases are:

lhc: 0.47064 mol.%
	with 0.00009 mol.% h2o
	with 0.99991 mol.% c3h8

s2: 0.52936 mol.%
	with 0.94446 mol.% h2o
	with 0.05554 mol.% c3h8


In [11]:
flash_iter4.__dict__

{'K_calc': array([[  1.11474717e+04,   1.00000000e+00,   1.00000000e+00,
           6.91912031e+03,   1.07549603e+04],
        [  3.95594984e-04,   1.00000000e+00,   1.00000000e+00,
           2.00391423e-03,   5.55402066e-02]]),
 'Nc': 2,
 'Np': 5,
 'P': 1.0,
 'T': 298.15,
 'alpha_calc': array([  0.00000000e+00,   1.00000000e-10,   4.70643334e-01,
          0.00000000e+00,   5.29356666e-01]),
 'completed': True,
 'compname': ['h2o', 'c3h8'],
 'compobjs': [<component_properties.Component at 0x10cb144e0>,
 'eos': {'aqueous': 'aqhb',
  'ice': 'ice',
  'lhc': 'srk',
  's1': 'hvdwpm',
  's2': 'hvdwpm',
  'vapor': 'srk'},
 'feed': array([ 0.5,  0.5]),
 'fug_list': [<aq_hb_eos.HegBromEos at 0x10cb14518>,
 'h2oexists': True,
 'h2oind': 0,
 'hyd_phases': {'s1': 3, 's2': 4},
 'iter_output': {},
 'monitor': [],
 'nonhyd_phases': [0, 1, 2],
 'phases': ['aqueous', 'vapor', 'lhc', 's1', 's2'],
 'ref_comp': array([  8.78166423e-05,   9.99912183e-01]),
 'ref_fug': array([ 0.00830268,  6.05532279]),
 

In [12]:
comps_iteralt = ['water', 'methane', 'ethane']
flash_iteralt = fc.FlashController(components=comps_iteralt,
                                phases=('aqueous', 'vapor', 'lhc', 's1', 's2'))
output = flash_iteralt.main_handler(
            compobjs=flash_iteralt.compobjs, 
            z=np.asarray([0.5, 0.25, 0.25]), 
            T=279.15, 
            P=P)
make_pretty_output(output, flash_iteralt)

Calculation considers the following phases:
['aqueous', 'vapor', 'lhc', 's1', 's2']

The stable phases are:

lhc: 0.41669 mol.%
	with 0.00014 mol.% h2o
	with 0.52626 mol.% ch4
	with 0.47360 mol.% c2h6

s1: 0.58331 mol.%
	with 0.85708 mol.% h2o
	with 0.05265 mol.% ch4
	with 0.09027 mol.% c2h6


In [13]:
comps_iter5 = ['water', 'methane', 'propane']
flash_iter5 = fc.FlashController(components=comps_iter5,
                                phases=('aqueous', 'vapor', 'lhc', 's1', 's2'))
output = flash_iter5.main_handler(
            compobjs=flash_iter5.compobjs, 
            z=np.asarray([0.5, 0.25, 0.25]), 
            T=T, 
            P=P,
            incipient_calc=True)
make_pretty_output(output, flash_iter5)

Calculation considers the following phases:
['aqueous', 'vapor', 'lhc', 's1', 's2']

The stable phases are:

lhc: 0.37484 mol.%
	with 0.00011 mol.% h2o
	with 0.42992 mol.% ch4
	with 0.56997 mol.% c3h8

vapor: 0.04236 mol.%
	with 0.00015 mol.% h2o
	with 0.82140 mol.% ch4
	with 0.17845 mol.% c3h8

s2: 0.58281 mol.%
	with 0.85784 mol.% h2o
	with 0.09276 mol.% ch4
	with 0.04941 mol.% c3h8


In [14]:
flash_iter5.__dict__

{'K_calc': array([[  7.39032718e+03,   1.41755172e+00,   1.00000000e+00,
           6.52071424e+03,   8.10682617e+03],
        [  3.96247307e-03,   1.91057954e+00,   1.00000000e+00,
           3.27747873e-01,   2.15748169e-01],
        [  4.07541962e-04,   3.13084487e-01,   1.00000000e+00,
           1.06710495e-04,   8.66852751e-02]]),
 'Nc': 3,
 'Np': 5,
 'P': 1.0,
 'T': 298.15,
 'alpha_calc': array([ 0.        ,  0.04235582,  0.37483646,  0.        ,  0.58280772]),
 'completed': True,
 'compname': ['h2o', 'ch4', 'c3h8'],
 'compobjs': [<component_properties.Component at 0x10cb21470>,
 'eos': {'aqueous': 'aqhb',
  'ice': 'ice',
  'lhc': 'srk',
  's1': 'hvdwpm',
  's2': 'hvdwpm',
  'vapor': 'srk'},
 'feed': array([ 0.5 ,  0.25,  0.25]),
 'fug_list': [<aq_hb_eos.HegBromEos at 0x10cb21550>,
 'h2oexists': True,
 'h2oind': 0,
 'hyd_phases': {'s1': 3, 's2': 4},
 'iter_output': {},
 'monitor': [],
 'nonhyd_phases': [0, 1, 2],
 'phases': ['aqueous', 'vapor', 'lhc', 's1', 's2'],
 'ref_comp': a

In [15]:
comps_iter6 = ['water', 'methane', 'ethane', 'propane']
flash_iter6 = fc.FlashController(components=comps_iter6,
                                phases=('aqueous', 'vapor', 'lhc', 's1', 's2'))
output = flash_iter6.main_handler(
            compobjs=flash_iter6.compobjs, 
            z=np.asarray([0.25, 0.25, 0.25, 0.25]), 
            T=T, 
            P=P,
            incipient_calc=True)
make_pretty_output(output, flash_iter6)

Calculation considers the following phases:
['aqueous', 'vapor', 'lhc', 's1', 's2']

The stable phases are:

lhc: 0.70958 mol.%
	with 0.00010 mol.% h2o
	with 0.31561 mol.% ch4
	with 0.34809 mol.% c2h6
	with 0.33619 mol.% c3h8

s2: 0.29042 mol.%
	with 0.86059 mol.% h2o
	with 0.08968 mol.% ch4
	with 0.01032 mol.% c2h6
	with 0.03941 mol.% c3h8


In [16]:
output

[array([[  9.97875473e-01,   1.01331977e-04,   1.01331977e-04,
           8.57503927e-01,   8.60586448e-01],
        [  1.48323112e-03,   3.15614112e-01,   3.15614112e-01,
           6.58240066e-02,   8.96827701e-02],
        [  4.72403396e-04,   3.48094526e-01,   3.48094526e-01,
           7.65662318e-02,   1.03220609e-02],
        [  1.68892610e-04,   3.36190030e-01,   3.36190031e-01,
           1.05834515e-04,   3.94087206e-02]]),
 array([  0.00000000e+00,   1.00000000e-10,   7.09584003e-01,
          0.00000000e+00,   2.90415997e-01]),
 array([[  8.12342313e+03,   1.00000000e+00,   1.00000000e+00,
           7.84727225e+03,   8.49274646e+03],
        [  3.87669571e-03,   1.00000000e+00,   1.00000000e+00,
           2.08558503e-01,   2.84153233e-01],
        [  1.11950200e-03,   1.00000000e+00,   1.00000000e+00,
           2.19958161e-01,   2.96530399e-02],
        [  4.14414289e-04,   1.00000000e+00,   1.00000000e+00,
           3.14805631e-04,   1.17221562e-01]]),
 6,
 8.310984417

In [17]:
flash_iter6.__dict__

{'K_calc': array([[  8.12342313e+03,   1.00000000e+00,   1.00000000e+00,
           7.84727225e+03,   8.49274646e+03],
        [  3.87669571e-03,   1.00000000e+00,   1.00000000e+00,
           2.08558503e-01,   2.84153233e-01],
        [  1.11950200e-03,   1.00000000e+00,   1.00000000e+00,
           2.19958161e-01,   2.96530399e-02],
        [  4.14414289e-04,   1.00000000e+00,   1.00000000e+00,
           3.14805631e-04,   1.17221562e-01]]),
 'Nc': 4,
 'Np': 5,
 'P': 1.0,
 'T': 298.15,
 'alpha_calc': array([  0.00000000e+00,   1.00000000e-10,   7.09584003e-01,
          0.00000000e+00,   2.90415997e-01]),
 'completed': True,
 'compname': ['h2o', 'ch4', 'c2h6', 'c3h8'],
 'compobjs': [<component_properties.Component at 0x10cb21c88>,
 'eos': {'aqueous': 'aqhb',
  'ice': 'ice',
  'lhc': 'srk',
  's1': 'hvdwpm',
  's2': 'hvdwpm',
  'vapor': 'srk'},
 'feed': array([ 0.25,  0.25,  0.25,  0.25]),
 'fug_list': [<aq_hb_eos.HegBromEos at 0x10cb21b70>,
 'h2oexists': True,
 'h2oind': 0,
 'hyd_pha

In [18]:
comps_iter7 = ['water', 'methane', 'ethane', 'propane']
flash_iter7 = fc.FlashController(components=comps_iter7,
                                phases=('aqueous', 'vapor', 'lhc', 's1', 's2'))
output = flash_iter7.main_handler(
            compobjs=flash_iter7.compobjs, 
            z=np.asarray([0.5, 0.1, 0.3, 0.1]), 
            T=T, 
            P=P,
            incipient_calc=True)
make_pretty_output(output, flash_iter7)

Calculation considers the following phases:
['aqueous', 'vapor', 'lhc', 's1', 's2']

The stable phases are:

lhc: 0.05622 mol.%
	with 0.00010 mol.% h2o
	with 0.17695 mol.% ch4
	with 0.58391 mol.% c2h6
	with 0.23905 mol.% c3h8

s1: 0.58181 mol.%
	with 0.85932 mol.% h2o
	with 0.04469 mol.% ch4
	with 0.09594 mol.% c2h6
	with 0.00006 mol.% c3h8

vapor: 0.36196 mol.%
	with 0.00010 mol.% h2o
	with 0.17695 mol.% ch4
	with 0.58391 mol.% c2h6
	with 0.23905 mol.% c3h8


In [19]:
comps_iter8 = ['water', 'methane', 'ethane', 'propane']
flash_iter8 = fc.FlashController(components=comps_iter8,
                                phases=('aqueous', 'vapor', 'lhc', 's1', 's2'))
output = flash_iter8.main_handler(
            compobjs=flash_iter8.compobjs, 
            z=np.asarray([0.4, 0.25, 0.25, 0.05]), 
            T=279.15, 
            P=P)
make_pretty_output(output, flash_iter8)

Calculation considers the following phases:
['aqueous', 'vapor', 'lhc', 's1', 's2']

The stable phases are:

lhc: 0.36673 mol.%
	with 0.00012 mol.% h2o
	with 0.40568 mol.% ch4
	with 0.50804 mol.% c2h6
	with 0.08615 mol.% c3h8

vapor: 0.14547 mol.%
	with 0.00014 mol.% h2o
	with 0.49429 mol.% ch4
	with 0.44632 mol.% c2h6
	with 0.05925 mol.% c3h8

s2: 0.48780 mol.%
	with 0.86304 mol.% h2o
	with 0.08708 mol.% ch4
	with 0.02443 mol.% c2h6
	with 0.02546 mol.% c3h8


In [20]:
flash_iter8.__dict__

{'K_calc': array([[  7.18822329e+03,   1.15760676e+00,   1.00000000e+00,
           7.25393943e+03,   7.30792348e+03],
        [  2.93005095e-03,   1.21841449e+00,   1.00000000e+00,
           1.23534490e-01,   2.14651612e-01],
        [  1.22749554e-03,   8.78513362e-01,   1.00000000e+00,
           1.80880156e-01,   4.80817126e-02],
        [  5.82419477e-04,   6.87717464e-01,   1.00000000e+00,
           4.07939438e-04,   2.95457484e-01]]),
 'Nc': 4,
 'Np': 5,
 'P': 1.0,
 'T': 298.15,
 'alpha_calc': array([ 0.        ,  0.14547135,  0.36672866,  0.        ,  0.48779999]),
 'completed': True,
 'compname': ['h2o', 'ch4', 'c2h6', 'c3h8'],
 'compobjs': [<component_properties.Component at 0x10cb21908>,
 'eos': {'aqueous': 'aqhb',
  'ice': 'ice',
  'lhc': 'srk',
  's1': 'hvdwpm',
  's2': 'hvdwpm',
  'vapor': 'srk'},
 'feed': array([ 0.42105263,  0.26315789,  0.26315789,  0.05263158]),
 'fug_list': [<aq_hb_eos.HegBromEos at 0x10fe4a080>,
 'h2oexists': True,
 'h2oind': 0,
 'hyd_phases': {'s

In [21]:
output

[array([[  9.97810825e-01,   1.36708795e-04,   1.18096205e-04,
           8.57953848e-01,   8.63036924e-01],
        [  1.39717832e-03,   4.94288455e-01,   4.05682393e-01,
           5.01157674e-02,   8.70803796e-02],
        [  7.33016300e-04,   4.46324631e-01,   5.08044888e-01,
           9.18952388e-02,   2.44276683e-02],
        [  5.89802896e-05,   5.92502058e-02,   8.61546231e-02,
           3.51458685e-05,   2.54550281e-02]]),
 array([ 0.        ,  0.14547135,  0.36672866,  0.        ,  0.48779999]),
 array([[  7.18822329e+03,   1.15760676e+00,   1.00000000e+00,
           7.25393943e+03,   7.30792348e+03],
        [  2.93005095e-03,   1.21841449e+00,   1.00000000e+00,
           1.23534490e-01,   2.14651612e-01],
        [  1.22749554e-03,   8.78513362e-01,   1.00000000e+00,
           1.80880156e-01,   4.80817126e-02],
        [  5.82419477e-04,   6.87717464e-01,   1.00000000e+00,
           4.07939438e-04,   2.95457484e-01]]),
 68,
 9.9478354983891872e-07]

In [22]:
output = flash_iter8.main_handler(
            compobjs=flash_iter8.compobjs, 
            z=np.asarray([0.44, 0.25, 0.25, 0.06]), 
            T=279.15, 
            P=P)

In [23]:
output

[array([[  9.97797433e-01,   1.38246506e-04,   1.16368170e-04,
           8.57107735e-01,   8.60721642e-01],
        [  1.42598698e-03,   5.10293123e-01,   4.03233032e-01,
           5.64602907e-02,   9.00007183e-02],
        [  7.09212505e-04,   4.24509175e-01,   4.95129644e-01,
           8.63999347e-02,   2.44127691e-02],
        [  6.73674204e-05,   6.50594550e-02,   1.01520955e-01,
           3.20396715e-05,   2.48648703e-02]]),
 array([ 0.        ,  0.064168  ,  0.42470081,  0.        ,  0.51113119]),
 array([[  7.26461008e+03,   1.18801140e+00,   1.00000000e+00,
           7.30390771e+03,   7.39654426e+03],
        [  2.99615114e-03,   1.26550678e+00,   1.00000000e+00,
           1.40019012e-01,   2.23197782e-01],
        [  1.21355941e-03,   8.57368611e-01,   1.00000000e+00,
           1.74499620e-01,   4.93058120e-02],
        [  5.62208401e-04,   6.40845116e-01,   1.00000000e+00,
           3.15596632e-04,   2.44923526e-01]]),
 54,
 9.8120718264070655e-07]

In [24]:
make_pretty_output(output, flash_iter8)

Calculation considers the following phases:
['aqueous', 'vapor', 'lhc', 's1', 's2']

The stable phases are:

lhc: 0.42470 mol.%
	with 0.00012 mol.% h2o
	with 0.40323 mol.% ch4
	with 0.49513 mol.% c2h6
	with 0.10152 mol.% c3h8

vapor: 0.06417 mol.%
	with 0.00014 mol.% h2o
	with 0.51029 mol.% ch4
	with 0.42451 mol.% c2h6
	with 0.06506 mol.% c3h8

s2: 0.51113 mol.%
	with 0.86072 mol.% h2o
	with 0.09000 mol.% ch4
	with 0.02441 mol.% c2h6
	with 0.02486 mol.% c3h8


In [25]:
comps_iter9 = ['methane', 'propane']
flash_iter9 = fc.FlashController(components=comps_iter9,
                                phases=('aqueous', 'vapor', 'lhc', 's1', 's2'))
output = flash_iter9.main_handler(
            compobjs=flash_iter9.compobjs, 
            z=np.asarray([0.5, 0.5]), 
            T=T, 
            P=P)
make_pretty_output(output, flash_iter9)

Calculation considers the following phases:
['vapor', 'lhc']

The stable phases are:

lhc: 0.82119 mol.%
	with 0.42999 mol.% ch4
	with 0.57001 mol.% c3h8

vapor: 0.17881 mol.%
	with 0.82154 mol.% ch4
	with 0.17846 mol.% c3h8


In [26]:
comps_iter10 = ['methane', 'ethane', 'propane']
flash_iter10 = fc.FlashController(components=comps_iter10,
                                phases=('aqueous', 'vapor', 'lhc', 's1', 's2'))
output = flash_iter10.main_handler(
            compobjs=flash_iter10.compobjs, 
            z=np.asarray([0.5, 0.25, 0.25]), 
            T=T, 
            P=P)
make_pretty_output(output, flash_iter10)

Calculation considers the following phases:
['vapor', 'lhc']

The stable phases are:

lhc: 0.65211 mol.%
	with 0.40863 mol.% ch4
	with 0.27580 mol.% c2h6
	with 0.31557 mol.% c3h8

vapor: 0.34789 mol.%
	with 0.67127 mol.% ch4
	with 0.20164 mol.% c2h6
	with 0.12709 mol.% c3h8


In [27]:
comps_iter_incipient = ['water', 'methane', 'ethane', 'propane']
flash_iter_incipient = fc.FlashController(components=comps_iter_incipient,
                                phases=('aqueous', 'vapor', 'lhc', 's1', 's2'))
output = flash_iter_incipient.main_handler(
            compobjs=flash_iter_incipient.compobjs, 
            z=np.asarray([0.25, 0.25, 0.25, 0.25]), 
            T=T, 
            P=P,
            incipient_calc=True)
make_pretty_output(output, flash_iter_incipient)

Calculation considers the following phases:
['aqueous', 'vapor', 'lhc', 's1', 's2']

The stable phases are:

lhc: 0.70958 mol.%
	with 0.00010 mol.% h2o
	with 0.31561 mol.% ch4
	with 0.34809 mol.% c2h6
	with 0.33619 mol.% c3h8

s2: 0.29042 mol.%
	with 0.86059 mol.% h2o
	with 0.08968 mol.% ch4
	with 0.01032 mol.% c2h6
	with 0.03941 mol.% c3h8


In [28]:
comps_iter_c3 = ['water', 'propane']
flash_iter_c3 = fc.FlashController(components=comps_iter_c3,
                                phases=('aqueous', 'lhc','s1', 's2'))
output = flash_iter_c3.main_handler(
            compobjs=flash_iter_c3.compobjs, 
            z=np.asarray([0.1, 0.9]), 
            T=273.15+2, 
            P=40,
            incipient_calc=True)
make_pretty_output(output, flash_iter_c3)

Calculation considers the following phases:
['aqueous', 'lhc', 's1', 's2']

The stable phases are:

lhc: 0.89420 mol.%
	with 0.00009 mol.% h2o
	with 0.99991 mol.% c3h8

s2: 0.10580 mol.%
	with 0.94447 mol.% h2o
	with 0.05553 mol.% c3h8


In [29]:
output

[array([[  9.99593593e-01,   8.54215080e-05,   9.98115327e-01,
           9.44466290e-01],
        [  4.06406673e-04,   9.99914578e-01,   1.88467306e-03,
           5.55337101e-02]]),
 array([ 0.        ,  0.89420097,  0.        ,  0.10579903]),
 array([[  1.13412813e+04,   1.00000000e+00,   7.13793093e+03,
           1.10565367e+04],
        [  3.93916347e-04,   1.00000000e+00,   1.88483407e-03,
           5.55384543e-02]]),
 3,
 2.2065232645650407e-07]