In [1]:
import flashalgorithm as fc
import component_properties as comp_table
import vlhc_srk_eos as hc
import aq_hb_eos as aq
import h_vdwpm_eos as hyd
import numpy as np

In [2]:
def make_pretty_output(output, flash):
    stable_dict = {phase: ii for ii, (phase, alpha) in 
                   enumerate(zip(flash.phases, flash.alpha_calc)) 
                   if alpha > 1e-10}
    print('Calculation considers the following phases:\n{0}\n'.format(flash.phases))
    print('The stable phases are:')
    for phase, index in stable_dict.items():
        print('\n{0}: {1:3.5f} mol.%'.format(phase, flash.alpha_calc[index]))
        for ii, comp in enumerate(flash.compobjs): 
            print('\twith {0:3.5f} mol.% {1}'.format(
                flash.x_calc[ii, index],
                comp.compname))

In [3]:
P = 70 # bar
T = 273.15 + 6 # Kelvin

In [4]:
comps_iter = ['water', 'methane', 'ethane', 'propane']
flash_iter = fc.FlashController(components=comps_iter,
                                phases=('aqueous', 'vapor', 'lhc', 's1', 's2'))
output = flash_iter.main_handler(
            compobjs=flash_iter.compobjs, 
            z=np.asarray([0.25, 0.25, 0.25, 0.25]), 
            T=T, 
            P=P)
make_pretty_output(output, flash_iter)

/Users/kdarnell/hydrateflash_KD/flashalgorithm.py:338: RuntimeWarning: overflow encountered in exp
  + s['a12']*np.log(P/T**2) + s['a13']/T**2)


Calculation considers the following phases:
['aqueous', 'vapor', 'lhc', 's1', 's2']

The stable phases are:

lhc: 0.67475 mol.%
	with 0.00011 mol.% h2o
	with 0.31561 mol.% ch4
	with 0.34809 mol.% c2h6
	with 0.33619 mol.% c3h8

s2: 0.29041 mol.%
	with 0.86058 mol.% h2o
	with 0.08969 mol.% ch4
	with 0.01032 mol.% c2h6
	with 0.03941 mol.% c3h8

vapor: 0.03484 mol.%
	with 0.00011 mol.% h2o
	with 0.31561 mol.% ch4
	with 0.34809 mol.% c2h6
	with 0.33619 mol.% c3h8


In [5]:
comps_iter_incipient = ['water', 'methane', 'ethane', 'propane']
flash_iter_incipient = fc.FlashController(components=comps_iter_incipient,
                                phases=('aqueous', 'vapor', 'lhc', 's1', 's2'))
output = flash_iter_incipient.main_handler(
            compobjs=flash_iter_incipient.compobjs, 
            z=np.asarray([0.25, 0.25, 0.25, 0.25]), 
            T=T, 
            P=P,
            incipient_calc=True)
make_pretty_output(output, flash_iter_incipient)

/Users/kdarnell/hydrateflash_KD/flashalgorithm.py:338: RuntimeWarning: overflow encountered in exp
  + s['a12']*np.log(P/T**2) + s['a13']/T**2)


Calculation considers the following phases:
['aqueous', 'vapor', 'lhc', 's1', 's2']

The stable phases are:

lhc: 0.70959 mol.%
	with 0.00011 mol.% h2o
	with 0.31561 mol.% ch4
	with 0.34809 mol.% c2h6
	with 0.33619 mol.% c3h8

s2: 0.29041 mol.%
	with 0.86059 mol.% h2o
	with 0.08968 mol.% ch4
	with 0.01032 mol.% c2h6
	with 0.03941 mol.% c3h8


In [6]:
s2h = flash_iter_incipient.fug_list[-1]
print(s2h.hydrate_size(T, P, s2h.v_H_0, s2h.kappa_func(s2h.Y_large)))
print(s2h.v_H_0)
print(s2h.kappa_func(s2h.Y_large))
print(s2h.Y_small, s2h.Y_large)
print(np.exp(-3e-6*(69)))
print(np.exp(2.029776e-4*(279.15-298.15) + 1.1851168e-7*(279.15-298.15)**2) + -1.879455e-10*(279.15-298.15)**3)

22.8338929203
22.9289121004
5.27868825456e-06
[  0.00000000e+00   8.76184817e-01   1.23630442e-03   3.99645400e-17] [ 0.          0.01921882  0.20142898  0.77847894]
0.999793021423
0.996194760702


In [7]:
comps_iter_incipient = ['water', 'methane', 'ethane', 'propane']
flash_iter_incipient = fc.FlashController(components=comps_iter_incipient,
                                phases=('aqueous', 'vapor', 'lhc', 's1', 's2'))
output = flash_iter_incipient.main_handler(
            compobjs=flash_iter_incipient.compobjs, 
            z=np.asarray([0.25, 0.25, 0.25, 0.25]), 
            T=273.15 + 15, 
            P=110,
            incipient_calc=True)
make_pretty_output(output, flash_iter_incipient)

/Users/kdarnell/hydrateflash_KD/flashalgorithm.py:338: RuntimeWarning: overflow encountered in exp
  + s['a12']*np.log(P/T**2) + s['a13']/T**2)


Calculation considers the following phases:
['aqueous', 'vapor', 'lhc', 's1', 's2']

The stable phases are:

lhc: 0.70995 mol.%
	with 0.00019 mol.% h2o
	with 0.31669 mol.% ch4
	with 0.34569 mol.% c2h6
	with 0.33742 mol.% c3h8

s1: 0.02311 mol.%
	with 0.85814 mol.% h2o
	with 0.06593 mol.% ch4
	with 0.07579 mol.% c2h6
	with 0.00015 mol.% c3h8

s2: 0.26694 mol.%
	with 0.86173 mol.% h2o
	with 0.08856 mol.% ch4
	with 0.01058 mol.% c2h6
	with 0.03913 mol.% c3h8


In [8]:
output

[array([[  9.98380506e-01,   1.89715576e-04,   1.89715576e-04,
           8.58137856e-01,   8.61731901e-01],
        [  1.14992601e-03,   3.16694770e-01,   3.16694770e-01,
           6.59252588e-02,   8.85585429e-02],
        [  3.52146776e-04,   3.45692699e-01,   3.45692699e-01,
           7.57891813e-02,   1.05835692e-02],
        [  1.17421250e-04,   3.37422815e-01,   3.37422815e-01,
           1.47704393e-04,   3.91259873e-02]]),
 array([ 0.        ,  0.        ,  0.70994649,  0.02310967,  0.26694384]),
 array([[  5.20135928e+03,   1.00000000e+00,   1.00000000e+00,
           4.52328664e+03,   4.54223103e+03],
        [  3.58882905e-03,   1.00000000e+00,   1.00000000e+00,
           2.08166553e-01,   2.79633739e-01],
        [  1.00683248e-03,   1.00000000e+00,   1.00000000e+00,
           2.19238594e-01,   3.06155416e-02],
        [  3.43950487e-04,   1.00000000e+00,   1.00000000e+00,
           4.37742756e-04,   1.15955370e-01]]),
 6,
 5.1892655352641943e-07]

In [31]:
comps_iter_incipient = ['water', 'methane', 'ethane']
flash_iter_incipient = fc.FlashController(components=comps_iter_incipient,
                                phases=('aqueous', 'vapor', 'lhc', 's1', 's2'))
output = flash_iter_incipient.main_handler(
            compobjs=flash_iter_incipient.compobjs, 
            z=np.asarray([0.25, 0.75*0.12, 0.75*0.88]), 
            T=273.15 + 6, 
            P=70,
            incipient_calc=True)
make_pretty_output(output, flash_iter_incipient)

Calculation considers the following phases:
['aqueous', 'vapor', 'lhc', 's1', 's2']

The stable phases are:

lhc: 0.20001 mol.%
	with 0.00009 mol.% h2o
	with 0.11335 mol.% ch4
	with 0.88657 mol.% c2h6

s1: 0.28997 mol.%
	with 0.86194 mol.% h2o
	with 0.03283 mol.% ch4
	with 0.10523 mol.% c2h6

vapor: 0.51002 mol.%
	with 0.00009 mol.% h2o
	with 0.11335 mol.% ch4
	with 0.88657 mol.% c2h6


In [13]:
import dill as pickle
pickle.dump(output, open('c1c3_1comp.pkl', 'wb'))