In [1]:
import flow_model as fm
import lookup_table as lt
import numpy as np
import dill as pickle

In [2]:
test_comp_mat = np.random.random([10, 4, 5])
test_comp_mat /= np.sum(test_comp_mat, axis=1)[:, np.newaxis, :]
test_S_mat = np.random.random([10, 5])
test_S_mat /= np.sum(test_S_mat, axis=1)[:, np.newaxis]
test_rho = np.random.random(5) ** (np.random.randn(5))

In [3]:
data_dict = pickle.load(open('80bar_12C_data_dict_test.pkl', 'rb'))
table = lt.quick_lookup(data_dict)
m = fm.model(table.flash)

In [ ]:
m.set_model(zL=[0, 0.95, 0.05, 0],
            zR=[0.98, 0.02, 0, 0],
            rho=[1, 0.1, 0.1, 0.9, 0.9],
            S_c=[0.1, 0.02, 0.02, 0.0, 0.0],
            Cor_exp=[2, 4, 4, 0, 0],
            mu=[1, 1e-2, 1e-2, 1, 1])

In [ ]:
m.run_model()

[[ 0.          0.          1.          0.          0.        ]
 [ 0.83559534  0.          0.16440466  0.          0.        ]
 [ 0.84428008  0.          0.15571992  0.          0.        ]]
[[  0.00000000e+00   9.50000000e-01   5.00000000e-02   0.00000000e+00]
 [  9.78764195e-01   2.11778247e-02   5.79798574e-05   0.00000000e+00]
 [  9.80000251e-01   1.99997493e-02   0.00000000e+00   0.00000000e+00]]
[ 1.          3.19327535  3.18515031]
[[ 0.          0.          1.          0.          0.        ]
 [ 0.76000356  0.          0.23999644  0.          0.        ]
 [ 0.82947195  0.          0.17052805  0.          0.        ]
 [ 0.8432862   0.          0.1567138   0.          0.        ]]
[[  0.00000000e+00   9.50000000e-01   5.00000000e-02   0.00000000e+00]
 [  9.67530435e-01   3.18193437e-02   6.50221262e-04   0.00000000e+00]
 [  9.77932294e-01   2.20280319e-02   3.96737037e-05   0.00000000e+00]
 [  9.79865898e-01   2.01340211e-02   8.10165922e-08   0.00000000e+00]]
[ 1.          2.9389