In [1]:
# import flow_model as fm
import flow_model_tgrad as fm
import lookup_table as lt
import numpy as np
import dill as pickle

In [2]:
test_comp_mat = np.random.random([10, 4, 5])
test_comp_mat /= np.sum(test_comp_mat, axis=1)[:, np.newaxis, :]
test_S_mat = np.random.random([10, 5])
test_S_mat /= np.sum(test_S_mat, axis=1)[:, np.newaxis]
test_rho = np.random.random(5) ** (np.random.randn(5))

In [3]:
# data_dict = pickle.load(open('80bar_12C_data_dict_test.pkl', 'rb'))
data_dict = pickle.load(open('110bar_13C_data_dict.pkl', 'rb'))
table = lt.quick_lookup(data_dict)
m = fm.model(table.flash, Nx=100, id='temp_May')

In [4]:
m.set_model(zL=[0, 0.9, 0.1, 0],
            zR=[1.0, 0, 0, 0],
            rho=[1, 0.1, 0.1, 0.9, 0.9],
            S_c=[0.1, 0.02, 0.02, 0.0, 0.0],
            Cor_exp=[2, 4, 4, 0, 0],
            mu=[1, 1e-2, 1e-2, 1, 1],
            T_grad=True,
            T_L=19.0,
            T_R=13.0)

In [5]:
m.run_model(cfl=0.025)

[[ 0.          0.          1.          0.          0.        ]
 [ 0.99555064  0.          0.00444936  0.          0.        ]
 [ 1.          0.          0.          0.          0.        ]]
[[  0.00000000e+00   9.00000000e-01   1.00000000e-01   0.00000000e+00]
 [  9.97519676e-01   2.23229161e-03   2.48032401e-04   0.00000000e+00]
 [  1.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]]
[ 1.          0.71816115  0.74068289]
[[ 0.          0.          1.          0.          0.        ]
 [ 0.76704775  0.          0.23295225  0.          0.        ]
 [ 0.99818466  0.          0.00181534  0.          0.        ]
 [ 1.          0.          0.          0.          0.        ]]
[[  0.00000000e+00   9.00000000e-01   1.00000000e-01   0.00000000e+00]
 [  9.68542727e-01   2.83044585e-02   3.15281468e-03   0.00000000e+00]
 [  9.97784448e-01   1.99883337e-03   2.16718861e-04   0.00000000e+00]
 [  9.99918355e-01   7.41793517e-05   7.46546745e-06   0.00000000e+00]]
[ 1.          3.1845

KeyboardInterrupt: 

In [ ]:
data_dict